print("Hi, My name is Ayush Atul Pathare (He/Him) and I am a sophmore at UCSC ")
print("My fav movie is Johnny English which is a comedy movie which ligthens my mood everytime I watch it")
print("Its about the fall of England and how our protagonist saves it. (with comedic twists of course)")
print("my fav food is a a chicken burger just because it tastes so nice and easy to make. ")
print("it might not be gourmet food but its alwasy pleasant to eat")
